name: Release System Version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19'
          cache: 'npm'
      - run: npm install
      - run: npm run build

      # create a zip file with all files required by the module to add to the release
      - name: Zip Files
        working-directory: ./
        run: zip -r ./system.zip ./assets ./fonts ./lang ./packs/*.db ./src ./tinymce index.js index.js.map style.css system.json template.json LICENSE.txt ChangeLog.md

      # Get the version from 'module.json'
      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::${GITHUB_REF#refs/*/}"

      # Generate changelog for release body
      - name: Changelog
        id: Changelog
        uses: scottbrenner/generate-changelog-action@master
        env:
          REPO: ${{ github.repository }}

      # Create a release for this specific version
      - name: Create Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # set this to false if you want to prevent updating existing releases
          name: ${{ steps.get-version.outputs.version }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json,./system.zip'
          tag: ${{ steps.get-version.outputs.version }}

      # Update the 'latest' release
      - name: Create Release
        id: create_latest_release
        uses: ncipollo/release-action@v1
        if: endsWith(github.event.base_ref, 'main')
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json,./system.zip'
          tag: latest